name: PyLint & Flake
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install pylint pandas pyyaml ansible ansible-lint flake8
      - name: PyLint with dynamic badge
        uses: Silleellie/pylint-github-action@v2
        with:
          lint-path: make_inventory.py
      - name: Lint with flake8
        run: |
          flake8 make_inventory.py --max-line-length=127 --count --statistics
